### GET request to example server
# @name health
# @no-log
GET http://localhost:8080/actuator/health
Accept: */*

### Register pet tag
# @name register-tag
# @no-log
POST http://localhost:8080/tag
Content-Type: application/json
Accept: application/json

{"value": "Vocal"}

### Retrieve pet tag by identifier
# @name find-tag-by-identifier
# @no-log
GET http://localhost:8080/tag/123e4567-e89b-12d3-a456-426614174001
Accept: application/json

